name: Commit Checks

on:
  push:
    branches:
      - 'main'
      - 'develop'
  workflow_dispatch:
    branches:
      - 'develop'
      - 'feature/*'
      - 'bugfix/*'

jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - uses: chartboost/ruff-action@v1

